sudo: false
language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy
    - python: pypy3

install:
  - pip install codecov

script:
  - coverage run -m unittest discover tests

after_success:
  - codecov -t 3d819dfb-67bf-43af-86e4-36318ea64b32