sudo: false
language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy
    - python: pypy3

install:
  - pip install codecov
  - pip install pytest pytest-cov

script:
  - pytest --cov=./

after_success:
  - codecov