sudo: false
language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy
    - python: pypy3

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install --upgrade pytest pytest-cov python-coveralls

script:
  - pytest

after_success:
  - coveralls
